# Inspired by: https://github.com/docascode/docfx-seed/blob/master/appveyor.yml
environment:
  git_user_email: normand.erwan@protonmail.com
  git_user_name: Erwan Normand
  auth_token:
    secure: 6ofAZV1tmD6f2ubY3R3QNjkxAg+zyniEYixAia6FjzKNhcQeY+mYOFAx2vWi8hdp
install:
- choco install docfx -y
build_script:
- cp README.md Documentation/index.md
- docfx Documentation/docfx.json
after_build:
- |
  git config --global user.email $env:git_user_email
  git config --global user.name $env:git_user_name

  git clone https://$($env:oauth_token)@github.com/NormandErwan/DocFxForUnity -b gh-pages gh-pages
  cd gh-pages

  shopt -s extglob
  rm -rf !(Unity)

  cp -r ../_site/* .
  git add --all 2>&1

  git commit -m "Documentation update"
  git push origin gh-pages