environment:
  oauth_token:
    secure: 6ofAZV1tmD6f2ubY3R3QNjkxAg+zyniEYixAia6FjzKNhcQeY+mYOFAx2vWi8hdp
  git_user_email: normand.erwan@protonmail.com
  git_user_name: Erwan Normand
install:
- choco install docfx -y
cache:
- gh-pages
- UnityCsReference
build_script:
- dotnet run
after_build:
- ps: >-
    cd gh-pages

    git config --global credential.helper store
    Add-Content "$env:USERPROFILE\.git-credentials" "https://$($env:oauth_token):x-oauth-basic@github.com`n"
    git config --global user.email $env:git_user_email
    git config --global user.name $env:git_user_name

    git push origin gh-pages -q